# Generated by Django 5.1.3 on 2024-11-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolvedcase',
            name='report_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
