# Generated by Django 5.1.3 on 2024-11-08 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0003_alter_resolvedcase_report_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(db_index=True, max_length=100)),
                ('case_id', models.CharField(db_index=True, max_length=100)),
                ('missing_person_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('status', models.CharField(db_index=True, max_length=50)),
                ('date_reported', models.DateField(blank=True, db_index=True, null=True)),
                ('reported_by', models.CharField(db_index=True, max_length=255)),
                ('age', models.IntegerField(blank=True, db_index=True, null=True)),
                ('gender', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('last_known_location', models.TextField(blank=True, db_index=True, null=True)),
                ('fir_number', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('police_officer_assigned', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('case_duration', models.IntegerField(blank=True, db_index=True, null=True)),
                ('resolution_summary', models.TextField(blank=True, db_index=True, null=True)),
                ('matching_fields', models.CharField(db_index=True, max_length=255)),
                ('closure_process', models.TextField(blank=True, db_index=True, null=True)),
                ('legal_and_police_involvement', models.TextField(blank=True, db_index=True, null=True)),
                ('hospital_and_forensic_involvement', models.TextField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('police_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Missing_persons.policestation')),
            ],
            options={
                'indexes': [models.Index(fields=['report_number', 'case_id'], name='Missing_per_report__210a20_idx'), models.Index(fields=['missing_person_name', 'status'], name='Missing_per_missing_0e829b_idx'), models.Index(fields=['date_reported', 'created_at'], name='Missing_per_date_re_5bd2f1_idx')],
            },
        ),
    ]
