# Generated by Django 5.1.3 on 2024-11-08 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0004_casereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casereport',
            name='police_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Missing_persons.chowki'),
        ),
        migrations.AlterField(
            model_name='casereport',
            name='report_number',
            field=models.CharField(db_index=True, editable=False, max_length=100),
        ),
    ]
