# Generated by Django 5.1.3 on 2024-11-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0005_alter_casereport_police_station_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casereport',
            name='match_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
