# Generated by Django 5.1.3 on 2024-11-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0006_casereport_match_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='casereport',
            name='missing_person_pk',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='casereport',
            name='unidentified_body_pk',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='casereport',
            name='unidentified_missing_person_pk',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
