# Generated by Django 5.1.3 on 2024-11-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0008_casereport_hospital_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolvedcase',
            name='relationship_with_victim',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
