# Generated by Django 5.1.3 on 2024-11-12 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0009_resolvedcase_relationship_with_victim'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_date', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.CharField(max_length=255)),
                ('missing_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_records', to='Missing_persons.missingperson')),
                ('unidentified_body', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='body_matches', to='Missing_persons.unidentifiedbody')),
                ('unidentified_missing_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missing_person_matches', to='Missing_persons.unidentifiedmissingperson')),
            ],
        ),
    ]
