# Generated by Django 5.1.3 on 2024-11-12 12:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0010_matchedrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchedrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchedrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
