# Generated by Django 5.1.3 on 2024-11-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0012_matchedrecord_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='case_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('Solved', 'Solved')], db_index=True, default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='unidentifiedbody',
            name='case_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('Solved', 'Solved')], db_index=True, default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='unidentifiedmissingperson',
            name='case_status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Resolved', 'Resolved'), ('Ongoing', 'Ongoing')], db_index=True, default='Pending', max_length=50),
        ),
    ]
