# Generated by Django 5.1.3 on 2024-11-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0013_missingperson_case_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
