# Generated by Django 5.1.3 on 2024-11-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missing_persons', '0014_match_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_status',
            field=models.CharField(choices=[('Partial', 'Partial'), ('Rejected', 'Rejected')], default='Partial', max_length=50),
        ),
        migrations.AddField(
            model_name='match',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
